### ISSUE TITLE
Fix tests in "test_repos.R"

### ISSUE THREAD

**Issue by statnmap** [statnmap/gitlabr#18]
![image](https://user-images.githubusercontent.com/21193866/92626168-d985e300-f2c9-11ea-9687-045818373178.png)

**Comment by KevCaz** [comment]
Hi @statnmap I only had a quick look at it so far, but was wondering why having `environment.yml.example` given that what is loaded is `environment.yml` (if it exists). I thought this would be a helper to set system variables but looks like it's not. I am quite confused right now but I will have a more careful look at it tomorrow.

**Comment by statnmap** [comment]
Hi,
This is because I do not want to share my own credential on Github. This allows to keep an example file in git, and you can have your own credential file. This is presented in the CONTRIBUTING.md file.  
Although this is also something to explain in the documentation (issue #10 )

**Comment by KevCaz** [comment]
I should have read the CONTRIBUTING, sorry for that.

**Comment by KevCaz** [comment]
Looks like all test with `project = 1` are tests designed for v3 and so should be removed according to #11 ?
When I removed them, `test(filter = "repos")` works seamlessly. 

```R
R> test(filter = "repos")                                                                                                                                                                     
Loading gitlabr
[1] "helper.R"
[1] "test user id: 5300390"
Testing gitlabr
✔ |  OK F W S | Context
✔ |  23       | test_repos [6.4 s]

══ Results ═════════════════════════════════════════════
Duration: 6.4 s

OK:       23
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by statnmap** [comment]
Ok thanks.
Then I think I will first need to clean the package with these v3 api calls, it will be easier check for the unit tests and doc.   
Indeed API v3 was removed in 2017. It is time for a big update !

**Comment by statnmap** [comment]
I did the big update considering the version used. I let the possibility for the v3 as an anticipation on what to do when a new api version will come...   
If you want to have a look at the remaining issues, you'll be highly welcome !  
I updated CONTRIBUTING to present for the additional needs.  
Thanks.

**Comment by KevCaz** [comment]
>  If you want to have a look at the remaining issues, you'll be highly welcome !
Sure! I will probably do so sooner than later!
