### ISSUE TITLE
Check functions examples to recommend "set style" strategy

### ISSUE THREAD

**Issue by statnmap** [statnmap/gitlabr#27]
Verify all functions examples to use those starting with `gl_` only, to avoid confusion.

Indeed, as stated in the README, we tried to provide a single connexion strategy.   
First set the connexion with : 
```r
# connect as a fixed user to a gitlab instance
my_gitlab <- gl_connection(
  gitlab_url = "https://gitlab.com",
  private_token = Sys.getenv("GITLAB_COM_TOKEN"))
# a function is returned
# its first argument is the request (name or function), optionally followed by parameters

# Set the connection for the session
set_gitlab_connection(my_gitlab)
```

Then use functions starting with `gl_*()` like `gl_list_projects(max_page = 2)`.

**Comment by LDalby** [comment]
I'll give this one a go.

**Comment by statnmap** [comment]
Every examples should be good now.

- [x] branches.R // test_branches.R
  - [x] 'project' first
  - [x] examples
- [x] files.R // test_files.R
  - [x] 'project' first
  - [x] examples
- [x] ci.R // test_ci.R
  - [x] 'project' first
  - [x] examples
- [x] comments // test_comments.R
  - [x] 'project' first
  - [x] examples
- [x] connect.R, gitlab_api.R, global_env.R // test_connection.R, test_gitlab_api.R
  - [x] 'project' first
  - [x] examples
- [x] issues.R // test_issues.R
  - [x] 'project' first
  - [x] examples
- [x] shiny_module_login.R // test_login_module.R
- [x] test_pagination.R
- [x] merge_request.R // test_merge_request.R
  - [x] 'project' first
  - [x] examples
- [x] projects_and_repos.R // test_projects_repos.R
  - [x] 'project' first
  - [x] examples
- [x] test_connection_env.R
