### ISSUE TITLE
default branch is master when it should be main

### ISSUE THREAD

**Issue by ginolhac** [statnmap/gitlabr#60]
Hello,

thanks for a great package, that provides many functionalities I need to interactive programmatically with our gitlab server.
Thanks to you, I can now create repo inside a group using `namespace_id`, the only remaining issue is that the default branch is still `master` despite setting the option and the argument to `main`.

``` r
library(gitlabr)
set_gitlab_connection(
  gitlab_url = "https://gitlab.lcsb.uni.lu",
  private_token = Sys.getenv("GITLAB_TOKEN"))
gitlabr_options_set("gitlabr.main", "main")
# create a new project
project_info <- gl_new_project(
  namespace_id = 120, # Sysbio
  path = "testgitlab3",
  default_branch = "main",
  initialize_with_readme = TRUE
)
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Many thanks in advance

{gitlabr} info:

```
    "gitlabr": {
      "Package": "gitlabr",
      "Version": "2.0.0.9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "statnmap",
      "RemoteRepo": "gitlabr",
      "RemoteRef": "main",
      "RemoteSha": "b3c4340c72ee473b19a36e14612b803d564c4718",
      "Hash": "d9bd3408a165e5284726ad9ff6f17d5d"
    }
```

**Comment by statnmap** [comment]
Hi Aurélien,

I tested the reprex on gitlab.com and on our internal GitLab forge, and it works as expected on my side.  
I do not know if this is a problem of local git version, or GitLab instance version.

- Could you retry with gitlab.com if you have an account ?
- Could you try again with your internal Gitlab now that it is probably updated... (sorry for the delay)

**Comment by ginolhac** [comment]
Hello,
indeed! thanks for the heads-up. It works now, the local gitlab instance here must have been updated and it is all fine now.
Sorry for the inconvenience

**Comment by statnmap** [comment]
No worries!
