### ISSUE TITLE
Add code coverage in gitlab-ci

### ISSUE THREAD

**Issue by statnmap** [statnmap/gitlabr#68]
Test coverage project CI/CD setting

Announced in 14.8

To simplify setting a test coverage pattern, in GitLab 15.0 the [project setting for test coverage parsing](https://docs.gitlab.com/ee/ci/pipelines/settings.html#add-test-coverage-results-using-project-settings-deprecated) is being removed.

Instead, using the project’s .gitlab-ci.yml, provide a regular expression with the `coverage` keyword to set testing coverage results in merge requests.

https://about.gitlab.com/blog/2022/04/18/gitlab-releases-15-breaking-changes/#test-coverage-project-cicd-setting

**Comment by ALanguillaume** [comment]
To make the coverage badge functional it is necessary to add the following line in the coverage stage section:

coverage: '/Coverage: \d+\.\d+/'

between script: and artifacts:.

This will allow the coverage to be parsed in the job log:

mypkg Coverage: 90.35%

Both

inst/gitlab-ci/check-coverage-pkgdown.yml

and

inst/gitlab-ci/check-coverage-pkgdown.-renv.yml

should be edited.

I will work on a PR asap.

Bisous

**Comment by statnmap** [comment]
Merged. Thank you.
