### ISSUE TITLE
project access token 

### ISSUE THREAD

**Issue by KatarzynaGraczyk** [statnmap/gitlabr#70]
Hi, I have a problem with creating PAT for my project. 
I set connection using: 

`set_gitlab_connection(
  gitlab_url = "https://gitlab.com/",
  private_token = "my_personal_access_token"
)`

and then I try to generate token to my project: 

`create_token <- gitlab(req = c("projects", project_id, "access_tokens"), 
                       verb = httr::POST, 
                       name = "my_token", 
                       scopes = list("api", "read_repository")
)`

As result, I am getting an error: BAD REQUEST
I have no idea what should I change. When I check a list of existing tokens it works fine.

**Comment by KatarzynaGraczyk** [comment]
Thank you for your response. I check that there is a possibility to generate a deploy token, but I have a similar error. When I try to use (for example):
`create_token <- gitlab(req = c("projects", project_id, "deploy_tokens"), 
                       verb = httr::POST, 
                       name = "token", 
                       scopes = list("read_repository", "write_registry"))
` I am getting an error BAD REQUEST, but in this case when ` scopes` have only one param `list("read_repository")` it works fine.

**Comment by statnmap** [comment]
Yes. It seems I cannot correctly pass two parameters. There are separated. I'll need to see how I can handle multiple inputs.

**Comment by KatarzynaGraczyk** [comment]
Hi, 
I figured out how pass two and more parameters in scopes. 
`deploy_token <- gitlab(req = c("projects", project_id, "deploy_tokens"),
                           verb = httr::POST,
                           name = "token",
                           scopes = list("read_repository, write_registry"))`
