### ISSUE TITLE
Separate vignette in different parts and transform as Rmd

### ISSUE THREAD

**Issue by statnmap** [statnmap/gitlabr#9]
Vignette would be more actual if created with {rmarkdown}.  
Also, we need to define some sections to be able to divide it in smaller pieces.

See https://github.com/ropensci/software-review/issues/113#issuecomment-305827917

Use this open project on Gitlab.com for the examples as in the Readme : https://gitlab.com/statnmap/repo.rtask

**Comment by LDalby** [comment]
Hi @statnmap 
I can see you labelled this issue _help wanted_ - I'd like to give it a go, but I can see you also have self-assigned it, so I just wanted to check if you have already done some work here? Otherwise please just assign it to me and I'll see what I can do over the next days.

Cheers, 
Lars

**Comment by statnmap** [comment]
Hi,
I did not started. Your contribution will be very welcome. 
For now, I did not think in the best way to separate things. Feel free to give suggestions.   
However, I think the first step would be to transform as Rmd.  
Thank you

**Comment by LDalby** [comment]
Cool. I'll give it a shot and I agree, the first step will to use Rmd. From there we can see if splitting things will be an improvement or not.

**Comment by LDalby** [comment]
So now the vignette knits as an rmarkdown::html_vignette and I have removed the old files.  
I would like to remove the section "convenience functions" and instead refer to the pkdown Reference section where we can have a subsection with these functions. I can see that the pkgdown site is build a bit differently than what I'm used to, so I could find the `_pkgdown.yaml` so I could add the section. Where is that file hiding?

**Comment by statnmap** [comment]
Nice !  Good idea.  
I did not put any `_pkgdown.yml` at the root as I did not changed the default behaviour of {pkgdown}.  
So if you want to add one, you're welcome to do so.

**Comment by LDalby** [comment]
Ahh I see. I guess I've reused my package template for so long that I didn't realize I used a non default pkgdown setup 😄 

I'll add a `_pkgdown.yaml` and put the section it it.  

Next I will start adding examples that will run using the repo you provided  - could you post/edit the link? It currently goes 404

**Comment by statnmap** [comment]
I did not realize the repo was private...  
I just opened it.

**Comment by LDalby** [comment]
I'm considering using either the _set_ style or the _parameter_ style instead of the _function-in-function_ style currently used in the quick start example. I think the _function-in-function_ style is the least intuitive for a new user, but maybe I'm wrong. What do you think @statnmap?

**Comment by statnmap** [comment]
This is a good idea. I was myself a little confused at the beginning with this object calling functions. As there are both implemented, we can use what is more common.   
Let's set the gitlab connection at the beginning and use the functions as is. At least for the README / quick start.  
_In the unit tests, I saw that some outputs where a little different though. I'll explore the corresponding issues later_

Could you please answer in #10 if you plan or have documented how to use "environment.yml" ?

**Comment by LDalby** [comment]
Cool, we go for the _set_ style. I'll update the README to follow this style too.
